export type Salary = { low: number; high: number; currency: 'CNY' | 'USD'; period: '月' | '年'; basis: string; evidence: '详情披露' | '索引参考'; note: string; source?: string };
export type MarketJob = { id: string; company: string; title: string; region: '国内' | '海外'; city: string; family: string; industry: string; experience: string; skills: string[]; description: string; caution?: string; url: string; source: string; status: '详情可访问' | '索引待核实'; salary?: Salary };
export const checkedAt = '2026-09-08';
export const marketJobs: MarketJob[] = [
  { id:'unicom', company:'联通数据智能有限公司', title:'AI产品经理（智能制造）', region:'国内', city:'地点待核实', family:'行业产品经理', industry:'智能制造', experience:'年限待核实', skills:['工业场景','产品规划','需求分析'], description:'面向制造企业规划 AI 产品，将产能分析、生产决策等业务需求转化为产品能力。', caution:'搜索索引有记录，详情访问受限；地点、薪资及是否仍在招聘需确认。', url:'https://www.zhaopin.com/jobdetail/CCL1493560780J40845479208.htm', source:'智联招聘', status:'索引待核实' },
  { id:'yongdao', company:'北京联合永道软件股份有限公司', title:'工业制造AI产品经理', region:'国内', city:'北京 · 通州', family:'行业产品经理', industry:'智能制造', experience:'5–10年 / 本科', skills:['工业经验','PRD','方案设计'], description:'结合制造业业务流程完成 AI 产品规划、需求文档和客户方案，参与落地支持。', url:'https://www.zhaopin.com/jobdetail/CC143220690J40948645104.htm', source:'智联招聘', status:'详情可访问' },
  { id:'beitong', company:'上海倍通医药科技咨询有限公司', title:'AI产品经理', region:'国内', city:'上海 · 黄浦', family:'行业产品经理', industry:'医药服务', experience:'正文要求3年以上产品经验', skills:['0→1产品','AI应用','业务需求'], description:'从客户业务需求出发规划 AI / 数据产品，推进方案设计和产品落地。', caution:'行业按雇主业务归类，具体医药应用场景需确认；页面标题经验不限，正文另有年限要求。', url:'https://www.zhaopin.com/jobdetail/CC242918510J40779292406.htm', source:'智联招聘', status:'详情可访问', salary:{low:30000,high:50000,currency:'CNY',period:'月',basis:'招聘标价',evidence:'索引参考',note:'移动页索引显示3–5万元；当前详情薪资隐藏，不能视为已确认报价。',source:'https://m.zhaopin.com/jobs/CC242918510J40779292406.htm'} },
  { id:'kaike', company:'开科唯识 · 深圳分公司', title:'AI产品经理', region:'国内', city:'北京', family:'行业产品经理', industry:'金融', experience:'3–5年 / 本科（平台摘要）', skills:['金融业务','AI产品','项目落地'], description:'参与金融客户 AI 产品规划与落地，将业务场景转化为需求。', caution:'人力驻场外包，甲方为国投泰康信托；不是甲方直接招聘。', url:'https://www.zhaopin.com/jobdetail/CC585923020J40897384603.htm', source:'智联招聘', status:'详情可访问', salary:{low:16000,high:18000,currency:'CNY',period:'月',basis:'招聘标价',evidence:'索引参考',note:'平台关联职位摘要显示1.6–1.8万元，岗位详情隐藏薪资，需招聘方确认。',source:'https://www.zhaopin.com/jobdetail/CC143220690J40948645104.htm'} },
  { id:'ccs', company:'中国通信建设集团设计院有限公司', title:'AI数智化解决方案专家', region:'国内', city:'地点请见原职位', family:'解决方案 / 售前', industry:'政企服务', experience:'正文要求3年以上售前经验', skills:['RAG','招投标','方案设计'], description:'面向通信及政企客户开展需求调研、技术方案和投标支持，涉及 AI 与数字化项目。', url:'https://www.zhaopin.com/jobdetail/CC237760810J40833223316.htm', source:'智联招聘', status:'详情可访问', salary:{low:8000,high:16000,currency:'CNY',period:'月',basis:'招聘标价',evidence:'索引参考',note:'平台关联职位摘要显示8000–16000元，当前详情未显示可核实薪资。',source:'https://www.zhaopin.com/jobdetail/CC143220690J40948645104.htm'} },
  { id:'ashley', company:'爱室丽家居 · 深圳分公司', title:'产品经理 · 智能制造系统', region:'国内', city:'深圳', family:'行业产品经理', industry:'智能制造', experience:'MES / APS 产品经历', skills:['MES / APS','制造流程','AI机会识别'], description:'围绕制造系统和运营流程推进产品工作，并识别 AI 在制造场景的应用机会。', caution:'企业内部数字化岗位，属于相邻机会，并非对外销售 AI 产品；平台触发验证码，详情待核实。', url:'https://www.liepin.com/job/1983927387.shtml', source:'猎聘', status:'索引待核实', salary:{low:30000,high:50000,currency:'CNY',period:'月',basis:'招聘标价',evidence:'索引参考',note:'搜索索引标注30–50k·13薪；未通过详情复核，不自动折算年薪。'} },
  { id:'anthropic-pm', company:'Anthropic', title:'Product Manager, Public Sector', region:'海外', city:'美国 · 华盛顿 / 远程友好', family:'行业产品经理', industry:'政企服务', experience:'约7年以上产品经历', skills:['公共部门','产品战略','客户需求'], description:'面向公共部门客户设计 AI 产品，将政府工作流与产品路线图结合。', caution:'要求 US person 身份；涉及安全许可与出差。远程友好不等于全球远程。', url:'https://job-boards.greenhouse.io/anthropic/jobs/5393452008', source:'官方招聘 · Greenhouse', status:'详情可访问', salary:{low:305000,high:385000,currency:'USD',period:'年',basis:'Annual Salary',evidence:'详情披露',note:'职位页标注 Annual Salary；不要与股权或完整总包混用。'} },
  { id:'sitreps-pm', company:'未披露雇主 · Sitreps代招', title:'AI Product Manager, Public Sector', region:'海外', city:'美国 · 华盛顿 / 旧金山', family:'行业产品经理', industry:'政企服务', experience:'偏好5年以上相关经验', skills:['AI治理','客户发现','产品落地'], description:'服务公共部门的 AI 安全产品，覆盖评测、运行时管控与 Agent 治理。', caution:'猎头代招，雇主名称保密；要求美国公民及安全许可资格，不提供完全远程。', url:'https://job-boards.greenhouse.io/sitrepsllc/jobs/4392930009', source:'招聘代理 · Greenhouse', status:'详情可访问', salary:{low:147000,high:185000,currency:'USD',period:'年',basis:'基本工资',evidence:'详情披露',note:'Base salary；股权、激励和福利另计。'} },
  { id:'openai-fde', company:'OpenAI', title:'Forward Deployed Engineer, Healthcare', region:'海外', city:'美国 · 旧金山', family:'FDE / 技术落地', industry:'医疗健康', experience:'6年以上相关技术经验', skills:['软件工程','医疗工作流','客户交付'], description:'深入医疗客户业务，将 AI 集成到真实工作流，承担端到端技术实现与交付。', caution:'混合办公，每周3天到岗，出差比例可能达50%；需要实际工程能力。', url:'https://openai.com/careers/forward-deployed-engineer-(fde)-healthcare-sf-san-francisco/', source:'OpenAI 官方招聘', status:'详情可访问', salary:{low:185000,high:300000,currency:'USD',period:'年',basis:'现金薪酬',evidence:'详情披露',note:'职位页 Compensation 范围；股权另计，不能等同完整总包。'} },
  { id:'anthropic-csm', company:'Anthropic', title:'Customer Success Manager, Industries', region:'海外', city:'美国 · 纽约', family:'客户成功', industry:'跨行业', experience:'6年以上CS / TAM / 解决方案经验', skills:['客户采用','API理解','业务价值'], description:'服务娱乐、保险、制造和零售客户，推动企业 AI 的采用、扩展与业务价值实现。', caution:'要求理解 API 集成和 AI 实施；薪酬页含销售 OTE 通用说明，奖金口径需确认。', url:'https://job-boards.greenhouse.io/anthropic/jobs/5068570008', source:'官方招聘 · Greenhouse', status:'详情可访问', salary:{low:200000,high:265000,currency:'USD',period:'年',basis:'年薪（奖金口径待确认）',evidence:'详情披露',note:'页面 Annual Salary 范围；未据此认定为纯底薪。'} },
  { id:'anthropic-sales', company:'Anthropic', title:'Enterprise Account Executive, Financial Services & Insurance', region:'海外', city:'日本 · 东京', family:'企业销售', industry:'金融', experience:'8年以上日本企业销售经验', skills:['金融客户','大客户销售','日语 / 英语'], description:'面向日本金融与保险企业推进 AI 商业合作，管理复杂企业采购与客户关系。', url:'https://job-boards.greenhouse.io/anthropic/jobs/5104753008', source:'官方招聘 · Greenhouse', status:'详情可访问' },
  { id:'openai-deploy', company:'OpenAI', title:'AI Deployment Manager (Builder)', region:'海外', city:'日本 · 东京', family:'实施交付 / 赋能', industry:'跨行业', experience:'4年以上客户服务或培训相关经验', skills:['企业赋能','Coding Agent','API'], description:'帮助企业团队掌握并采用 AI 开发工具，通过培训与实施推动实际使用。', caution:'混合办公，每周3天到岗；不是纯行政项目管理岗位。', url:'https://openai.com/careers/ai-deployment-manager-(builder)-tokyo-tokyo-japan/', source:'OpenAI 官方招聘', status:'详情可访问' },
];
export function filterJobs(query: string, region: string, family: string, industry: string, salaryOnly: boolean) {
  const terms = query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
  return marketJobs.filter(j => (region === '全部' || j.region === region) && (family === '全部' || j.family === family) && (industry === '全部' || j.industry === industry) && (!salaryOnly || j.salary?.evidence === '详情披露') && terms.every(t => [j.company,j.title,j.city,j.family,j.industry,j.description,...j.skills].join(' ').toLocaleLowerCase().includes(t)));
}
export function salaryText(s: Salary) { return `${s.currency === 'CNY' ? '¥' : '$'}${s.low / 1000}–${s.high / 1000}k`; }
